### PR TITLE
Issue 35 fix logos

### PR DESCRIPTION
**Pull request by vanlankveldthijs**
Resolves issue #35 and issue #34

eScience logo is always there (as second logo where applicable). It is scaled down slightly compared to the carpentries logo. Is its size correct?
This logo links to the eScience Center website.

Code Refinery logo replaces the carpentries logo if the carpentry type is set to "cr".
This logo links to the escience academy workshop page. Should probably be fixed so it points to the current workshop page...

Added dummy favicons for the "ds" and "cr" carpentries. Otherwise it will complain about missing icons. Note that these are currently the SWC icons, so they should still be fixed!

### CODE REVIEW

**Comment by mkuzak** [comment]
Thnank you @vanlankveldthijs , it turns out we need to use the full 'Netherlands Science Center Logo" can you use [this](https://nlesc.sharepoint.com/:u:/s/training/EYomjqehYKNLhYpo0iB5qogBVNoI7pvr8pdNOOQOwXpTBQ?e=LUuaT6) logo instead?

**Comment by mkuzak** [comment]
@vanlankveldthijs  thank you ;)
we need the logo with "Netherlands" on it.

**Comment by vanlankveldthijs** [comment]
This should be fixed in the latest commit; if you want to check that @mkuzak

**Comment by mkuzak** [comment]
Looks great. One thing to make it better, since the eScience Center log will always be there and others will change, it makes more sense to have eScience Center logo as first one (most to the left). Can you move it?

**Comment by mkuzak** [comment]
When setting carpentry: ds and curriculum ds-cr, the cr logo does not show up.

**Pull request merged**
